/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DiscographyRouteImport } from './routes/discography'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReleasesReleaseSlugRouteImport } from './routes/releases.$releaseSlug'
import { Route as ArtistsArtistSlugRouteImport } from './routes/artists.$artistSlug'

const DiscographyRoute = DiscographyRouteImport.update({
  id: '/discography',
  path: '/discography',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReleasesReleaseSlugRoute = ReleasesReleaseSlugRouteImport.update({
  id: '/releases/$releaseSlug',
  path: '/releases/$releaseSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsArtistSlugRoute = ArtistsArtistSlugRouteImport.update({
  id: '/artists/$artistSlug',
  path: '/artists/$artistSlug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/discography': typeof DiscographyRoute
  '/artists/$artistSlug': typeof ArtistsArtistSlugRoute
  '/releases/$releaseSlug': typeof ReleasesReleaseSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/discography': typeof DiscographyRoute
  '/artists/$artistSlug': typeof ArtistsArtistSlugRoute
  '/releases/$releaseSlug': typeof ReleasesReleaseSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/discography': typeof DiscographyRoute
  '/artists/$artistSlug': typeof ArtistsArtistSlugRoute
  '/releases/$releaseSlug': typeof ReleasesReleaseSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/discography'
    | '/artists/$artistSlug'
    | '/releases/$releaseSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/discography'
    | '/artists/$artistSlug'
    | '/releases/$releaseSlug'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/discography'
    | '/artists/$artistSlug'
    | '/releases/$releaseSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  DiscographyRoute: typeof DiscographyRoute
  ArtistsArtistSlugRoute: typeof ArtistsArtistSlugRoute
  ReleasesReleaseSlugRoute: typeof ReleasesReleaseSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/discography': {
      id: '/discography'
      path: '/discography'
      fullPath: '/discography'
      preLoaderRoute: typeof DiscographyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/releases/$releaseSlug': {
      id: '/releases/$releaseSlug'
      path: '/releases/$releaseSlug'
      fullPath: '/releases/$releaseSlug'
      preLoaderRoute: typeof ReleasesReleaseSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists/$artistSlug': {
      id: '/artists/$artistSlug'
      path: '/artists/$artistSlug'
      fullPath: '/artists/$artistSlug'
      preLoaderRoute: typeof ArtistsArtistSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  DiscographyRoute: DiscographyRoute,
  ArtistsArtistSlugRoute: ArtistsArtistSlugRoute,
  ReleasesReleaseSlugRoute: ReleasesReleaseSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
